### ISSUE TITLE
Clp Optimizer not supporting Julia v1.2

### ISSUE THREAD

**Issue by mattuntergassmair** [JuliaPOMDP/IncrementalPruning.jl#14]
Installation of IncrementalPruning.jl in Julia v1.2 fails due to Clp compatibility issues. Replacing Clp.Optimizer with a different optimizer should solve the issue.

**Comment by rejuvyesh** [comment]
We should make the Optimizer choice part of the solver and propagate that choice to the `dominate` function. This way we can keep a sensible default that works generally with the users responsible for choosing the one more appropriate for their problem?

**Comment by MaximeBouton** [comment]
I think this has been fixed by #15
