### ISSUE TITLE
OptimizerFactory not defined

### ISSUE THREAD

**Issue by mykelk** [JuliaPOMDP/IncrementalPruning.jl#24]
The build is failing since vanilla.jl does not include a definition of OptimizerFactory. Perhaps this should be imported from JuMP.jl?

**Comment by zsunberg** [comment]
I think this is because we bumped JuMP to v0.21 without actually upgrading the code (#20 and #21 combo). I just pulled* JuMP back to 0.19 and we'll see if it works.

It would be nice for someone to actually bump it to the latest version of JuMP.

*what is the opposite of "bumped"? haha

**Comment by zsunberg** [comment]
Ok, master should pass test now, but it would be nice to upgrade to a newer version of JuMP

**Comment by mykelk** [comment]
Perhaps we can drop the type tag on the third field?
```julia
mutable struct PruneSolver <: Solver
    max_iterations::Int64
    tolerance::Float64
    optimizer_factory::OptimizerFactory
end
```

**Comment by zsunberg** [comment]
Seems like that might work - I am not very familiar with this code.
