### ISSUE TITLE
Use POMDPToolbox.AlphaVectorPolicy?

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/IncrementalPruning.jl#5]
Hi @ajkeith , would it make sense for your solver to return an AlphaVectorPolicy from POMDPToolbox rather than the custom policy it returns now? There may be advantages to the policy you return now, but just wanted to check. We are converting QMDP and SARSOP to return this standard AlphaVectorPolicy, so it might make sense for the sake of consistency.

If you decide to make the change, you may want to wait until POMDPToolbox 0.2.7 is registered since I think we are adding a few things to AlphaVectorPolicy in that.

**Comment by ajkeith** [comment]
That would probably make sense. Right now the custom policy is just for convenience based on how I set up the dominate/filter functions. At the very least, I should be able to just convert to an AlphaVectorPolicy before returning to match the other solvers (longer term it would probably be better just to avoid the custom policy type entirely). I'll take a look.

**Comment by ajkeith** [comment]
Switched to AlphaVectorPolicy
