### ISSUE TITLE
Broken with Jump >= 0.19

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/IncrementalPruning.jl#9]
```julia
using POMDPs
using POMDPModels
using IncrementalPruning

m = TigerPOMDP()

solver = PruneSolver()
p = solve(solver, m)
```

```
ERROR: LoadError: The solver= keyword is no longer available in JuMP 0.19 and later. See the JuMP documentation (http://www.juliaopt.org/JuMP.jl/latest/) for latest syntax.
```

**Comment by zsunberg** [comment]
#11 is a temporary fix - we should update to the new JuMP syntax when someone gets a chance

**Comment by zsunberg** [comment]
@ajkeith would you be interested in fixing thins?

**Comment by ajkeith** [comment]
Yes, thanks for pinging me! I'll take a look

**Comment by zsunberg** [comment]
Thanks - we appreciate it!

**Comment by ajkeith** [comment]
Updated the code to work with JuMP 0.19 and uncapped the project toml

**Comment by zsunberg** [comment]
Awesome! Thanks for fixing it. btw I used this in a presentation a few weeks back to talk about alpha vectors - it worked great.

**Comment by zsunberg** [comment]
I'll update the registry to include the new version

**Comment by ajkeith** [comment]
Great, good to hear!
